apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ include "service.name" . }}
    helm.sh/chart: {{ include "service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    qred.se/env: {{ .Values.environment }}
    qred.se/app: {{ include "service.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

data:
  database_url: {{ .Values.database.url }}
  database_user: {{ .Values.database.username }}
